### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by sirolf2009** [nickman/jmxlocal#1]
Can you release this to the maven central?
#2

**Comment by nickman** [comment]
Sure. Give me a couple of days, I am a bit swamped at the moment.

**Comment by nickman** [comment]
Never mind. It's done.
If you're using jmxlocal, you might also be interested in jvm-name:  https://github.com/nickman/jvm-name

Thanks for the PR. Nice work on the POM.

**Comment by sirolf2009** [comment]
Cheers, I'll look into it.
I've implemented your library in https://github.com/sirolf2009/caesar. I'm using your library to support reconnecting to local jvm's, using the groovy url pattern thing
